Webtech_Office/Webtech_Office/Models/ViewModels/NovidadesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Webtech_Office.Models
{
    public class NovidadesViewModel
    {
        public HOME_Novidades Novidades { get; set; }

        public List<HOME_NovidadesTexto> NovidadesTexto { get; set; }

        public List<ImageUpload> File { get; set; }

        public List<FileDocumento> FileDocumento { get; set; }
        public List<CONF_Idioma> Idioma { get; set; }


        public NovidadesViewModel()
        {

            Novidades = new HOME_Novidades();

            NovidadesTexto = new List<HOME_NovidadesTexto>();

            File = new List<ImageUpload>();
            FileDocumento = new List<FileDocumento>();

            Idioma = new List<CONF_Idioma>();

        }

    }
}

Webtech_Office/Webtech_Office/Controllers/HomePageController.cs
using DataTables.Mvc;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Linq.Dynamic;
using System.Net;
using System.Threading.Tasks;
using System.Web.Mvc;
using Webtech_Office.Models;

namespace Webtech_Office.Controllers
{
    public class HomePageController : Controller
    {

        private CMS_DbContext db = new CMS_DbContext();


        // GET: HomePage
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Banner()
        {
            return View();
        }

        public ActionResult Novidades()
        {
            return View();
        }

        public ActionResult Parceiros()
        {
            return View();
        }




        public JsonResult ListaBanner([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel)
        {


            IQueryable<HOME_HomePageBanner> query = db.HOME_HomePageBanner
                .Include("HOME_HomePageBannerTexto")

                .Include("CONF_Idioma")
                .Where(m => m.HOME_HomePageBannerTexto.Any(mt => mt.CONF_Idioma.Codigo.ToUpper().Equals("PT")));

            var totalCount = query.Count();

            #region Filtering  
            // Applicar filtros para pesquisas 
            if (requestModel.Search.Value != string.Empty)
            {
                var value = requestModel.Search.Value.Trim();

                /*
                  query = 

                      query.Include(m => m.MEDI_MediaTexto.Where(mt => mt.Descricao.Contains(value)))
                           .Include(m => m.MEDI_MediaTexto.Where(mt => mt.Introducao.Contains(value)));
                           */

            }

            var filteredCount = query.Count();

            #endregion Filtering  


            #region Sorting  
            // Sorting  
            var sortedColumns = requestModel.Columns.GetSortedColumns();
            var orderByString = String.Empty;

            foreach (var column in sortedColumns)
            {
                orderByString += orderByString != String.Empty ? "," : "";
                orderByString += (column.Data) + (column.SortDirection == Column.OrderDirection.Ascendant ? " asc" : " desc");
            }

            query = query.OrderBy(x => orderByString == string.Empty ? "Titulo asc" : orderByString);

            #endregion Sorting  

            // Paging  
            query = query.Skip(requestModel.Start).Take(requestModel.Length);



            var data =
                query.Select(m => new
                {

                    Titulo = (m.HOME_HomePageBannerTexto.FirstOrDefault().Titulo.Length <= 70 ? m.HOME_HomePageBannerTexto.FirstOrDefault().Titulo
                        : m.HOME_HomePageBannerTexto.FirstOrDefault().Titulo.Substring(0, 70) + "..."),
                    Introducao = (m.HOME_HomePageBannerTexto.FirstOrDefault().Introducao.Length <= 70 ? m.HOME_HomePageBannerTexto.FirstOrDefault().Introducao
                        : m.HOME_HomePageBannerTexto.FirstOrDefault().Titulo.Substring(0, 70) + "..."),


                    Imagem = m.Id,
                    Link = m.HOME_HomePageBannerTexto.FirstOrDefault().Link,
                    PDF = m.HOME_HomePageBannerTexto.FirstOrDefault().PDF,
                    Activo = m.Activo,
                    Opcoes = m.Id

                }).ToList();


            return Json(new DataTablesResponse(requestModel.Draw, data, filteredCount, totalCount), JsonRequestBehavior.AllowGet);





        }

        [HttpGet]
        public ActionResult CriarHomePageBanner()
        {
            HomePageBannerViewModel model = new HomePageBannerViewModel();
            foreach (CONF_Idioma idioma in db.CONF_Idioma.ToList())
            {
                HOME_HomePageBannerTexto HomePageTexto = new HOME_HomePageBannerTexto()
                {
                    CONF_Idioma = idioma
                };
                model.HomePageBannerTexto.Add(HomePageTexto);
                ImageUpload file = new ImageUpload();
                model.File.Add(file);
                FileDocumento doc = new FileDocumento();
                model.FileDocumento.Add(doc);

            }




            return View("CriarHomePageBanner", model);

        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CriarHomePageBanner(HomePageBannerViewModel model)
        {


            model.HomePageBanner.DataCriacao = DateTime.Now;
            model.HomePageBanner.DataModificacao = DateTime.Now;

            int i = 0;
            foreach (ImageUpload file in model.File)
            {
                if (file.File != null)
                {
                    string directory = "~/Content/files/anexos/";
                    if (!Directory.Exists(Server.MapPath("~/Content/files/anexos/")))
                    {
                        Directory.CreateDirectory(Server.MapPath("~/Content/files/anexos/"));
                    }

                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.File.FileName.ToLower());
                    file.File.SaveAs(Path.Combine(Server.MapPath(directory), fileName));

                    model.HomePageBannerTexto[i].Imagem = fileName;

                }
                i++;

            }
            i = 0;
            foreach (FileDocumento docFile in model.FileDocumento)
            {

                if (docFile.File != null)
                {
                    string directory = "~/Content/files/anexos/";
                    if (!Directory.Exists(Server.MapPath("~/Content/files/anexos/")))
                    {
                        Directory.CreateDirectory(Server.MapPath("~/Content/files/anexos/"));
                    }



                    var fileName = Path.GetFileName(docFile.File.FileName);
                    docFile.File.SaveAs(Path.Combine(Server.MapPath(directory), fileName));

                    model.HomePageBannerTexto[i].PDF = fileName;

                }
                i++;

            }




            i = 0;
            List<CONF_Idioma> idioma = db.CONF_Idioma.ToList();
            foreach (HOME_HomePageBannerTexto textos in model.HomePageBannerTexto)
            {

                textos.HOME_HomePageBanner = model.HomePageBanner;
                textos.CONF_Idioma = idioma[i];
                textos.Introducao = System.Net.WebUtility.HtmlDecode(textos.Introducao);

                i++;

            }



            model.HomePageBanner.HOME_HomePageBannerTexto = model.HomePageBannerTexto;
            db.HOME_HomePageBanner.Add(model.HomePageBanner);
            db.SaveChanges();


            /*
            if (!ModelState.IsValid)
            {
                ViewBag.TipoMidia = new SelectList(db.MIDI_TipoMidia.ToList(), "Id", "Descricao");
                ModelState.AddModelError("", "Impossivel criar o Conteudo.");
                return View("CriarMidiaConteudo", model);
            }*/

            return RedirectToAction("Index");

        }


        [HttpGet]
        public ActionResult DetalhesHomePageBanner(int? id)
        {
            HOME_HomePageBanner model = db.HOME_HomePageBannerTexto.Include("CONF_Idioma").Include("HOME_HomePageBanner")
               .Select(x => x.HOME_HomePageBanner).Where(c => c.Id == id).FirstOrDefault();



            HomePageBannerViewModel BannerModel = new HomePageBannerViewModel();
            BannerModel.HomePageBanner = model;
            BannerModel.HomePageBannerTexto = model.HOME_HomePageBannerTexto.ToList();
            BannerModel.Idioma = model.HOME_HomePageBannerTexto.Select(x => x.CONF_Idioma).ToList();

            return PartialView("_DetalhesHomePageBanner", BannerModel);

        }


        [HttpGet]
        public ActionResult EditarHomePageBanner(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            HOME_HomePageBanner model = db.HOME_HomePageBannerTexto.Include("CONF_Idioma").Include("HOME_HomePageBanner")
              .Select(x => x.HOME_HomePageBanner).Where(c => c.Id == id).FirstOrDefault();


            if (model == null)
            {
                return HttpNotFound();
            }
            HomePageBannerViewModel BannerModel = new HomePageBannerViewModel();
            BannerModel.HomePageBanner = model;
            BannerModel.HomePageBannerTexto = model.HOME_HomePageBannerTexto.ToList();
            BannerModel.Idioma = model.HOME_HomePageBannerTexto.Select(x => x.CONF_Idioma).ToList();


            foreach (CONF_Idioma idioma in db.CONF_Idioma.ToList())
            {


                ImageUpload file = new ImageUpload();
                BannerModel.File.Add(file);
                FileDocumento doc = new FileDocumento();
                BannerModel.FileDocumento.Add(doc);

            }


            return View("EditarHomePageBanner", BannerModel);


        }


        [HttpPost]
        public ActionResult EditarHomePageBanner(HomePageBannerViewModel model)
        {


            int i = 0;
            foreach (ImageUpload file in model.File)
            {
                if (file.File != null)
                {
                    string directory = "~/Content/files/anexos/";
                    if (!Directory.Exists(Server.MapPath("~/Content/files/anexos/")))
                    {
                        Directory.CreateDirectory(Server.MapPath("~/Content/files/anexos/"));
                    }

                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.File.FileName.ToLower());
                    file.File.SaveAs(Path.Combine(Server.MapPath(directory), fileName));

                    model.HomePageBannerTexto[i].Imagem = fileName;

                }
                i++;

            }
            i = 0;
            foreach (FileDocumento docFile in model.FileDocumento)
            {

Webtech_Office/Webtech_Office/Views/HomePage/CriarHomePageBanner.cshtml
@model Webtech_Office.Models.HomePageBannerViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Inserir Banner</title>
    <script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/jquery")"></script>
    <script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/jqueryval")"></script>
    <script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Bundles/js")"></script>
    <script type="text/javascript" src="~/Scripts/ckeditor/ckeditor.js"></script>
</head>
<body>

    <div class="modal-dialog create-modal">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h3 class="modal-title">Inserir Banner</h3>
            </div>

            <div class="modal-body">
               @using (Html.BeginForm("CriarHomePageBanner", "HomePage", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", id = "formRegisto", role = "form" }))
               {
                @Html.AntiForgeryToken()
               
                    <!-- Custom Tabs -->
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="panel panel-primary list-panel" id="list-panel">

                        <div class="panel-heading" style="height:60px;">

                            <h4>Informação</h4>

                        </div>


                        <div class="panel-body  ">

                            <div class="form-horizontal">

                              






                                <div class="form-group">
                                    @for (int i = 0; i < Model.HomePageBannerTexto.Count; i++)
                                    {
                                        @Html.HiddenFor(model => @Model.HomePageBannerTexto[i].CONF_Idioma.Id)



                                        <div class="col-md-12">
                                            @Html.LabelFor(model => model.HomePageBannerTexto[i].Titulo, htmlAttributes: new { @class = "control-label " })
                                            (@Html.DisplayFor(model => model.HomePageBannerTexto[i].CONF_Idioma.Descricao))
                                            @Html.ValidationMessageFor(model => model.HomePageBannerTexto[i].Titulo, "", new { @class = "text-danger" })
                                            @Html.EditorFor(model => model.HomePageBannerTexto[i].Titulo, new { htmlAttributes = new { @class = "form-control" } })

                                        </div>


                                    }
                                </div>

                                <div class="form-group">
                                    @for (int i = 0; i < Model.HomePageBannerTexto.Count; i++)
                {
                                        @Html.HiddenFor(model => @Model.HomePageBannerTexto[i].CONF_Idioma.Id)



                                        <div class="col-md-12">
                                            @Html.LabelFor(model => model.HomePageBannerTexto[i].Introducao, htmlAttributes: new { @class = "control-label " })
                                            (@Html.DisplayFor(model => model.HomePageBannerTexto[i].CONF_Idioma.Descricao))
                                            @Html.ValidationMessageFor(model => model.HomePageBannerTexto[i].Introducao, "", new { @class = "text-danger" })
                                            @Html.EditorFor(model => model.HomePageBannerTexto[i].Introducao, new { htmlAttributes = new { @class = "form-control" } })

                                        </div>


                                    }

                                </div>
                                <div class="form-group">

                                    @for (int i = 0; i < Model.HomePageBannerTexto.Count; i++)
                                    {
                                        @Html.HiddenFor(model => @Model.HomePageBannerTexto[i].CONF_Idioma.Id)



                                        <div class="col-md-12">
                                            @Html.LabelFor(model => model.HomePageBannerTexto[i].Link, htmlAttributes: new { @class = "control-label " })
                                            (@Html.DisplayFor(model => model.HomePageBannerTexto[i].CONF_Idioma.Descricao))
                                            @Html.ValidationMessageFor(model => model.HomePageBannerTexto[i].Link, "", new { @class = "text-danger" })
                                            @Html.EditorFor(model => model.HomePageBannerTexto[i].Link, new { htmlAttributes = new { @class = "form-control" } })

                                        </div>


                                    }
                                </div>

                                <div class="form-group">

                                    @for (int i = 0; i < Model.FileDocumento.Count; i++)
                                    {
                                        @Html.HiddenFor(model => model.HomePageBannerTexto[i].CONF_Idioma.Id)



                                        <div class="col-md-12">

                                            <label class="control-label "><b>PDF</b></label>
                                            (@Html.DisplayFor(model => model.HomePageBannerTexto[i].CONF_Idioma.Descricao))
                                            @Html.EditorFor(model => @Model.FileDocumento[i].File, new { htmlAttributes = new { @class = "form-control", name = "File", id = "File" } })



                                        </div>


                                    }
                                </div>
                                <div class="form-group">
                                    @for (int i = 0; i < Model.File.Count; i++)
                                    {
                                        @Html.HiddenFor(model => model.HomePageBannerTexto[i].CONF_Idioma.Id)



                                        <div class="col-md-12" id="@String.Concat("divImg_", i)">

                                            <label class="control-label "><b>Imagem</b></label>
                                            (@Html.DisplayFor(model => model.HomePageBannerTexto[i].CONF_Idioma.Descricao))
                                            @Html.EditorFor(model => @Model.File[i].File, new { htmlAttributes = new { @class = "form-control ", name = @String.Concat("File_", i), @id = @String.Concat("File_", i) } })
                                            <img id="@String.Concat("Img_", i)" class="img-preview">
                                            <script type="text/javascript">
                                                $("@String.Concat("#File_", i+"__File")").change(function () {
                                                    readURL(this, "@String.Concat("#Img_", i)");
                                                });
                                            </script>

                                        </div>


                                    }
                                </div>
                    </div>
                 </div>
                   </div>

                  


                       
                            <div class="form-horizontal">

                                <div class="form-group">

                                    <div class="col-md-12">
                                        @Html.LabelFor(model => model.HomePageBanner.Activo, htmlAttributes: new { @class = "control-label " })
                                        &nbsp;&nbsp;&nbsp;
                                        @Html.ValidationMessageFor(model => model.HomePageBanner.Activo, "", new { @class = "text-danger" })
                                        @Html.CheckBoxFor(model => model.HomePageBanner.Activo, new { htmlAttributes = new { @class = "form-control" } })

                                    </div>
                                </div>



                            </div>
             



                  


             
                        <div class="modal-footer">
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <button type="button" class="btn btn-default" data-dismiss="modal" id="CancelRedirect">Fechar</button>
                                    <input type="submit" class="btn btn-primary" value="Confirmar" />
                                </div>
                            </div>
                        </div>
                     

                   
               }
              
          </div>
      </div>
   </div>

            <style type="text/css">
                .img-preview {
                    height: 250px;
                    width: auto;
                    display: none;
                }
            </style>

            <script type="text/javascript">

                                                $("#CancelRedirect").click(
                                                    function () {
                                                        window.location = "/HomePage/Index";
                                                    }
                                                );



                                                function readURL(input, img) {
                                                    for (var i = 0; i < input.files.length; i++) {
                                                        if (input.files[i]) {
                                                            var reader = new FileReader();

                                                            reader.onload = function (e) {
                                                                $(img).attr('src', e.target.result);
                                                                $(img).css("display", "block");
                                                            }
                                                            reader.readAsDataURL(input.files[i]);
                                                        }
                                                    }


                                                }

                                                $(document).ready(
                                                    function () {

                                                        $("#MapaPartilhado").change(

                                                            function () {
                                                                var mapa = $("#MapaPartilhado").val();
                                                                document.getElementById("#DivMapaPreview").innerHTML = "";
                                                                document.getElementById("#DivMapaPreview").innerHTML = mapa;
                                                            }
                                                        );
                                                    }

                                                );




            </script>
</body>
</html>

Webtech_Office/Webtech_Office/Views/HomePage/_ImagemDestaquesPreviewPartial.cshtml
@model Webtech_Office.Models.ImagemViewModel
@{
    Layout = null;
}
<script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/jquery")"></script>
<script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/jqueryval")"></script>
<script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Bundles/js")"></script>
<script type="text/javascript" src="~/Scripts/ckeditor/ckeditor.js"></script>

<div class="modal-dialog create-modal" style="width:70%!important;margin-top:20px;">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <h3 class="modal-title"><i class="fa fa-cart-plus" aria-hidden="true"></i>&nbsp;&nbsp;Imagem Loja</h3>
        </div>

        <img src="@String.Concat(@Url.Content("~/Content/files/anexos/"), Model.Imagem)" style="width:100%;height:500px;" />

    </div>
</div>

Webtech_Office/Webtech_Office/Views/HomePage/_ImagemHomePagePreviewPartial.cshtml
@model Webtech_Office.Models.ImagemViewModel
@{
    Layout = null;
}
<script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/jquery")"></script>
<script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/jqueryval")"></script>
<script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Bundles/js")"></script>
<script type="text/javascript" src="~/Scripts/ckeditor/ckeditor.js"></script>

<div class="modal-dialog create-modal" style="width:70%!important;margin-top:20px;">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <h3 class="modal-title"><i class="fa fa-cart-plus" aria-hidden="true"></i>&nbsp;&nbsp;Imagem Loja</h3>
        </div>

        <img src="@String.Concat(@Url.Content("~/Content/files/anexos/"), Model.Imagem)" style="width:100%;height:500px;" />

    </div>
</div>

Webtech_Office/Webtech_Office/Views/HomePage/_ImagemPromocoesPreviewPartial.cshtml
@model Webtech_Office.Models.ImagemViewModel
@{
    Layout = null;
}
<script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/jquery")"></script>
<script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/jqueryval")"></script>
<script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Bundles/js")"></script>
<script type="text/javascript" src="~/Scripts/ckeditor/ckeditor.js"></script>

<div class="modal-dialog create-modal" style="width:70%!important;margin-top:20px;">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <h3 class="modal-title"><i class="fa fa-cart-plus" aria-hidden="true"></i>&nbsp;&nbsp;Imagem Loja</h3>
        </div>

        <img src="@String.Concat(@Url.Content("~/Content/files/anexos/"), Model.Imagem)" style="width:100%;height:500px;" />

    </div>
</div>