Webtech_Office/Webtech_Office/Models/ViewModels/MediaViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Webtech_Office.Models
{
    public class MediaViewModel
    {
        public MEDI_TipoMedia TipoMedia { get; set; }
        public MEDI_Media Media { get; set; }
        public List<MEDI_MediaTexto> MediaTexto { get; set; }
        public MEDI_Anexo Anexo { get; set; }
        public List<MEDI_AnexoTexto> AnexoTexto{get;set;}

        public List<ImageUpload> File { get; set; }
        public List<FileDocumento> FileDocumento { get; set; }

        [Required(ErrorMessage="Obrigatório")]
        public string Data { get; set; }

        public MediaViewModel()
        {
            TipoMedia = new MEDI_TipoMedia();
            Media = new MEDI_Media();
            MediaTexto = new List<MEDI_MediaTexto>();
            Anexo = new MEDI_Anexo();
            AnexoTexto = new List<MEDI_AnexoTexto>();
            File = new List<ImageUpload>();
            FileDocumento = new List<Models.FileDocumento>();
        }
    }
}

Webtech_Office/Webtech_Office/Controllers/MediaController.cs
using DataTables.Mvc;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.SqlServer;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Webtech_Office.Models;

namespace Webtech_Office.Controllers
{
    [Authorize]
    public class MediaController : Controller
    {
        private CMS_DbContext db = new CMS_DbContext();

        public JsonResult ListaMediaIntroducao([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel)
        {


            IQueryable<MEDI_MediaIntroducao> query = db.MEDI_MediaIntroducao
                .Include("MEDI_MediaIntroducaoTexto")

                .Include("CONF_Idioma")
                .Where(m => m.MEDI_MediaIntroducaoTexto.Any(mt => mt.CONF_Idioma.Codigo.ToUpper().Equals("PT")));

            var totalCount = query.Count();

            #region Filtering  
            // Applicar filtros para pesquisas 
            if (requestModel.Search.Value != string.Empty)
            {
                var value = requestModel.Search.Value.Trim();

                /*
                  query = 

                      query.Include(m => m.MEDI_MediaTexto.Where(mt => mt.Descricao.Contains(value)))
                           .Include(m => m.MEDI_MediaTexto.Where(mt => mt.Introducao.Contains(value)));
                           */

            }

            var filteredCount = query.Count();

            #endregion Filtering  


            #region Sorting  
            // Sorting  
            var sortedColumns = requestModel.Columns.GetSortedColumns();
            var orderByString = String.Empty;

            foreach (var column in sortedColumns)
            {
                orderByString += orderByString != String.Empty ? "," : "";
                orderByString += (column.Data) + (column.SortDirection == Column.OrderDirection.Ascendant ? " asc" : " desc");
            }

            query = query.OrderBy(x => orderByString == string.Empty ? "Titulo asc" : orderByString);

            #endregion Sorting  

            // Paging  
            query = query.Skip(requestModel.Start).Take(requestModel.Length);



            var data =
                query.Select(m => new
                {

                    Titulo = (m.MEDI_MediaIntroducaoTexto.FirstOrDefault().Titulo.Length <= 70 ? m.MEDI_MediaIntroducaoTexto.FirstOrDefault().Titulo
                        : m.MEDI_MediaIntroducaoTexto.FirstOrDefault().Titulo.Substring(0, 70) + "..."),
                    Introducao = (m.MEDI_MediaIntroducaoTexto.FirstOrDefault().Introducao.Length <= 70 ? m.MEDI_MediaIntroducaoTexto.FirstOrDefault().Introducao
                        : m.MEDI_MediaIntroducaoTexto.FirstOrDefault().Titulo.Substring(0, 70) + "..."),


                    Imagem = m.Id,

                    Activo = m.Activo,
                    Opcoes = m.Id

                }).ToList();


            return Json(new DataTablesResponse(requestModel.Draw, data, filteredCount, totalCount), JsonRequestBehavior.AllowGet);





        }


        [HttpGet]
        public ActionResult CriarMediaIntroducao()
        {
            MediaIntroducaoViewModel model = new MediaIntroducaoViewModel();
            model.MediaIntroducao.Activo = true;
            foreach (CONF_Idioma idioma in db.CONF_Idioma.ToList())
            {
                MEDI_MediaIntroducaoTexto MediaTexto = new MEDI_MediaIntroducaoTexto()
                {
                    CONF_Idioma = idioma
                };
                model.MediaIntroducaoTexto.Add(MediaTexto);
                ImageUpload file = new ImageUpload();
                model.File.Add(file);
                FileDocumento doc = new FileDocumento();
                model.FileDocumento.Add(doc);

            }

            return View("CriarMediaIntroducao", model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CriarMediaIntroducao(MediaIntroducaoViewModel model)
        {


            model.MediaIntroducao.DataCriacao = DateTime.Now;
            model.MediaIntroducao.DataModificacao = DateTime.Now;

            int i = 0;
            foreach (ImageUpload file in model.File)
            {
                if (file.File != null)
                {
                    string directory = "~/Content/files/anexos/";
                    if (!Directory.Exists(Server.MapPath("~/Content/files/anexos/")))
                    {
                        Directory.CreateDirectory(Server.MapPath("~/Content/files/anexos/"));
                    }

                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.File.FileName.ToLower());
                    file.File.SaveAs(Path.Combine(Server.MapPath(directory), fileName));

                    model.MediaIntroducaoTexto[i].Imagem = fileName;

                }
                i++;

            }
            i = 0;
            foreach (FileDocumento docFile in model.FileDocumento)
            {

                if (docFile.File != null)
                {
                    string directory = "~/Content/files/anexos/";
                    if (!Directory.Exists(Server.MapPath("~/Content/files/anexos/")))
                    {
                        Directory.CreateDirectory(Server.MapPath("~/Content/files/anexos/"));
                    }



                    var fileName = Path.GetFileName(docFile.File.FileName);
                    docFile.File.SaveAs(Path.Combine(Server.MapPath(directory), fileName));

                    model.MediaIntroducaoTexto[i].PDF = fileName;

                }
                i++;

            }




            i = 0;
            List<CONF_Idioma> idioma = db.CONF_Idioma.ToList();
            foreach (MEDI_MediaIntroducaoTexto textos in model.MediaIntroducaoTexto)
            {

                textos.MEDI_MediaIntroducao = model.MediaIntroducao;
                textos.CONF_Idioma = idioma[i];
                textos.Introducao = System.Net.WebUtility.HtmlDecode(textos.Introducao);

                i++;

            }



            model.MediaIntroducao.MEDI_MediaIntroducaoTexto = model.MediaIntroducaoTexto;
            db.MEDI_MediaIntroducao.Add(model.MediaIntroducao);
            db.SaveChanges();


            /*
            if (!ModelState.IsValid)
            {
                ViewBag.TipoMedia = new SelectList(db.MIDI_TipoMedia.ToList(), "Id", "Descricao");
                ModelState.AddModelError("", "Impossivel criar o Conteudo.");
                return View("CriarMediaConteudo", model);
            }*/

            return RedirectToAction("Index");

        }

        [HttpGet]
        public ActionResult DetalhesMediaIntroducao(int? id)
        {
            MEDI_MediaIntroducao model = db.MEDI_MediaIntroducaoTexto.Include("CONF_Idioma").Include("MEDI_MediaIntroducao")
               .Select(x => x.MEDI_MediaIntroducao).Where(c => c.Id == id).FirstOrDefault();



            MediaIntroducaoViewModel IntroducaoModel = new MediaIntroducaoViewModel();
            IntroducaoModel.MediaIntroducao = model;
            IntroducaoModel.MediaIntroducaoTexto = model.MEDI_MediaIntroducaoTexto.ToList();
            IntroducaoModel.Idioma = model.MEDI_MediaIntroducaoTexto.Select(x => x.CONF_Idioma).ToList();

            return PartialView("_DetalhesMediaIntroducao", IntroducaoModel);

        }
        [HttpGet]
        public ActionResult EditarMediaIntroducao(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MEDI_MediaIntroducao model = db.MEDI_MediaIntroducaoTexto.Include("CONF_Idioma").Include("MEDI_MediaIntroducao")
              .Select(x => x.MEDI_MediaIntroducao).Where(c => c.Id == id).FirstOrDefault();


            if (model == null)
            {
                return HttpNotFound();
            }
            MediaIntroducaoViewModel IntroducaoModel = new MediaIntroducaoViewModel();
            IntroducaoModel.MediaIntroducao = model;
            IntroducaoModel.MediaIntroducaoTexto = model.MEDI_MediaIntroducaoTexto.ToList();
            IntroducaoModel.Idioma = model.MEDI_MediaIntroducaoTexto.Select(x => x.CONF_Idioma).ToList();


            foreach (CONF_Idioma idioma in db.CONF_Idioma.ToList())
            {


                ImageUpload file = new ImageUpload();
                IntroducaoModel.File.Add(file);
                FileDocumento doc = new FileDocumento();
                IntroducaoModel.FileDocumento.Add(doc);

            }


            return View("EditarMediaIntroducao", IntroducaoModel);


        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditarMediaIntroducao(MediaIntroducaoViewModel model)
        {


            int i = 0;
            foreach (ImageUpload file in model.File)
            {
                if (file.File != null)
                {
                    string directory = "~/Content/files/anexos/";
                    if (!Directory.Exists(Server.MapPath("~/Content/files/anexos/")))
                    {
                        Directory.CreateDirectory(Server.MapPath("~/Content/files/anexos/"));
                    }

                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.File.FileName.ToLower());
                    file.File.SaveAs(Path.Combine(Server.MapPath(directory), fileName));

                    model.MediaIntroducaoTexto[i].Imagem = fileName;

                }
                i++;

            }
            i = 0;
            foreach (FileDocumento docFile in model.FileDocumento)
            {

                if (docFile.File != null)
                {
                    string directory = "~/Content/files/anexos/";
                    if (!Directory.Exists(Server.MapPath("~/Content/files/anexos/")))
                    {

Webtech_Office/Webtech_Office/Views/Media/ApagarMediaConteudo.cshtml
@model Webtech_Office.Models.MediaViewModel

<script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/jquery")"></script>
<script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/jqueryval")"></script>
<script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Bundles/js")"></script>
<script type="text/javascript" src="~/Scripts/ckeditor/ckeditor.js"></script>


<div class="modal-dialog create-modal">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title">Apagar Média</h4>
        </div>

        <div class="modal-body">
            <!-- Custom Tabs -->
            <div class="panel panel-primary list-panel" id="list-panel">

                <div class="panel-heading" style="height:60px;">

                    <h4>Informação</h4>

                </div>


                <div class="panel-body  ">

                    <div class="form-horizontal">

                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


                        <div class="form-group">


                            <div class="col-md-6">
                                <label class="control-label">Típo&nbsp;<b style="color:red">*</b></label>


                                @Html.ValidationMessageFor(model => model.Media.TipoMidia, "", new { @class = "text-danger" })
                                @Html.DropDownListFor(model => model.Media.TipoMidia,
                                                                    (IEnumerable<SelectListItem>)ViewBag.TipoMedia, "Seleccionar Tipo", new { @class = "selectpicker form-control", @readonly = "readonly" })

                            </div>
                            <div class="col-md-6">
                                <label class="control-label">Data&nbsp;<b style="color:red">*</b></label>


                                @Html.ValidationMessageFor(model => model.Media.Data, "", new { @class = "text-danger" })
                                @Html.EditorFor(model => model.Media.Data, new { htmlAttributes = new { @class = "form-control" } })

                            </div>
                        </div>


                        @for (int i = 0; i < Model.MediaTexto.Count; i++)
                        {
                            @Html.HiddenFor(model => @Model.MediaTexto[i].CONF_Idioma.Id)

                            <div class="form-group">

                                <div class="col-md-12">
                                    @Html.LabelFor(model => model.MediaTexto[i].Descricao, htmlAttributes: new { @class = "control-label " })
                                    @Html.DisplayFor(model => model.MediaTexto[i].CONF_Idioma.Descricao)
                                    @Html.ValidationMessageFor(model => model.MediaTexto[i].Descricao, "", new { @class = "text-danger" })
                                    @Html.EditorFor(model => model.MediaTexto[i].Descricao, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                                </div>
                            </div>

                        }

                        @for (int i = 0; i < Model.MediaTexto.Count; i++)
                        {
                            @Html.HiddenFor(model => @Model.MediaTexto[i].CONF_Idioma.Id)

                            <div class="form-group">

                                <div class="col-md-12">
                                    @Html.LabelFor(model => model.MediaTexto[i].Introducao, htmlAttributes: new { @class = "control-label " })
                                   
                                    @Html.ValidationMessageFor(model => model.MediaTexto[i].Introducao, "", new { @class = "text-danger" })
                                    @Html.EditorFor(model => model.MediaTexto[i].Introducao, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                                </div>
                            </div>

                        }

                        @for (int i = 0; i < Model.MediaTexto.Count; i++)
                        {
                            @Html.HiddenFor(model => @Model.MediaTexto[i].CONF_Idioma.Id)

                            <div class="form-group">
                                <div class="col-md-12">
                                    @Html.LabelFor(model => model.MediaTexto[i].Conteudo, htmlAttributes: new { @class = "control-label " })
                                    
                                    @Html.ValidationMessageFor(model => model.MediaTexto[i].Conteudo, "", new { @class = "text-danger" })
                                    @Html.TextAreaFor(model => model.MediaTexto[i].Conteudo, new { @rows = 200, @class = "form-control", id = i })
                                    <script>
                                                $(document).ready(
                                                    function () {
                                                        CKEDITOR.replace('@i');
                                                        CKEDITOR.Add;
                                                    }
                                                );

                                    </script>
                                </div>
                            </div>
                        }



                        @for (int i = 0; i < Model.MediaTexto.Count; i++)
                        {
                            @Html.HiddenFor(model => @Model.MediaTexto[i].CONF_Idioma.Id)

                            <div class="form-group">

                                <div class="col-md-12">
                                    @Html.LabelFor(model => model.MediaTexto[i].Link, htmlAttributes: new { @class = "control-label " })
                                  
                                    @Html.ValidationMessageFor(model => model.MediaTexto[i].Link, "", new { @class = "text-danger" })
                                    @Html.EditorFor(model => model.MediaTexto[i].Link, new { htmlAttributes = new { @class = "form-control" } })

                                </div>
                            </div>

                        }
                        <div class="form-group">
                            <div class="col-md-12">
                                <hr />
                            </div>
                        </div>

                        <div class=" form-group">
                            @for (int i = 0; i < Model.MediaTexto.Count; i++)
                            {
                                @Html.HiddenFor(model => model.MediaTexto[i].CONF_Idioma.Id)



                                <div class="col-md-12 ">



                                    <label class="control-label "><b>Anexo</b></label>
                                   
                                    @if (!String.IsNullOrWhiteSpace(Model.MediaTexto[i].PDF))
                                    {
                                        <p style="cursor:pointer;padding:0;"><i class="fa fa-file" aria-hidden="true" style="font-size:20px;"> </i>&nbsp;&nbsp;@Html.DisplayFor(model => model.MediaTexto[i].PDF)</p>

                                    }
                                    else
                                    {
                                        <p style="padding:0"><i class="fa fa-file" aria-hidden="true" style="color:red;font-size:20px;"></i>&nbsp;&nbsp;Sem ficheiro anexado</p>
                                    }

                                </div>





                            }
                        </div>

                        <div class="form-group">
                            <div class="col-md-12">
                                <hr />
                            </div>
                        </div>

                        <div class="form-group">
                            @for (int i = 0; i < Model.MediaTexto.Count; i++)
                            {



                                <div class="col-md-12" id="@String.Concat("divImg_", i)">

                                    <label class="control-label "><b>Imagem</b></label>
                                    
                                    @if (!String.IsNullOrWhiteSpace(Model.MediaTexto[i].Imagem))
                                    {
                                        <p>
                                            <img id="@String.Concat("Img_", i)" src="@String.Concat(@Url.Content("~/Content/files/anexos/"),  Model.MediaTexto[i].Imagem)"
                                                 class="img-preview">
                                        </p>
                                    }
                                    else
                                    {
                                        <p>
                                            <img id="@String.Concat("Img_", i)" src="@Url.Content("~/Content/img/sem-img.jpeg")"
                                                 class="img-preview">
                                        </p>
                                    }






                                </div>



                            }
                        </div>






                    </div>



                </div>
            </div>

            <div class="form-group">

                <div class="col-md-12">
                    @Html.LabelFor(model => model.Media.Destaque, htmlAttributes: new { @class = "control-label" })
                    &nbsp;&nbsp;&nbsp;
                    @Html.ValidationMessageFor(model => model.Media.Destaque, "", new { @class = "text-danger" })
                    @Html.CheckBoxFor(model => model.Media.Destaque, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                </div>
            </div>

            <div class="form-group">

                <div class="col-md-12">
                    @Html.LabelFor(model => model.Media.PartilhaFacebook, htmlAttributes: new { @class = "control-label " })
                    &nbsp;&nbsp;&nbsp;
                    @Html.ValidationMessageFor(model => model.Media.PartilhaFacebook, "", new { @class = "text-danger" })
                    @Html.CheckBoxFor(model => model.Media.PartilhaFacebook, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                </div>
            </div>
            <div class="form-group">

                <div class="col-md-12">
                    @Html.LabelFor(model => model.Media.PartilhaTwitter, htmlAttributes: new { @class = "control-label " })
                    &nbsp;&nbsp;&nbsp;
                    @Html.ValidationMessageFor(model => model.Media.PartilhaTwitter, "", new { @class = "text-danger" })
                    @Html.CheckBoxFor(model => model.Media.PartilhaTwitter, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                </div>
            </div>

            <div class="form-group">

                <div class="col-md-12">
                    @Html.LabelFor(model => model.Media.Activo, htmlAttributes: new { @class = "control-label " })
                    &nbsp;&nbsp;&nbsp;
                    @Html.ValidationMessageFor(model => model.Media.Activo, "", new { @class = "text-danger" })
                    @Html.CheckBoxFor(model => model.Media.Activo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                </div>
            </div>

        </div>



        @using (@Html.BeginForm("ApagarMediaConteudoConfirmar", "Media", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {

            @Html.HiddenFor(x => x.Media.Id)
            <div class="modal-footer">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" id="btnMidiaCancel" class="btn btn-default" data-dismiss="modal">Fechar</button>
                        <input type="submit" class="btn btn-primary" value="Apagar" />
                    </div>
                </div>
            </div>

        }

    </div>
</div>

Webtech_Office/Webtech_Office/Views/Media/_ApagarMediaIntroducaoPartial.cshtml
@model Webtech_Office.Models.MediaIntroducaoViewModel

<script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/jquery")"></script>
<script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/jqueryval")"></script>
<script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Bundles/js")"></script>
<script type="text/javascript" src="~/Scripts/ckeditor/ckeditor.js"></script>
<section class="content-header">
    <h1>
        <i class="fa fa-cart-plus" aria-hidden="true"></i> Medias

    </h1>
</section>


<div class="modal-dialog create-modal">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title">Apagar Introdução</h4>
        </div>

        <div class="modal-body">
    <!-- Custom Tabs -->

    <div class="panel panel-primary list-panel" id="list-panel">

        <div class="panel-heading" style="height:60px;">

            <h4>Informação</h4>

        </div>


        <div class="panel-body  ">
            <div class="form-horizontal">

                <div class="form-group  ">
                    @for (int i = 0; i < Model.MediaIntroducaoTexto.Count; i++)
                    {
                        @Html.HiddenFor(model => @Model.MediaIntroducaoTexto[i].CONF_Idioma.Id)

                        <div class="col-md-12">


                            @Html.LabelFor(model => model.MediaIntroducaoTexto[i].Titulo, htmlAttributes: new { @class = "control-label " })
                           
                            @Html.ValidationMessageFor(model => model.MediaIntroducaoTexto[i].Titulo, "", new { @class = "text-danger" })
                            @Html.EditorFor(model => model.MediaIntroducaoTexto[i].Titulo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })


                        </div>

                    }
                </div>


                <div class="form-group ">
                    @for (int i = 0; i < Model.MediaIntroducaoTexto.Count; i++)
                    {
                        @Html.HiddenFor(model => @Model.MediaIntroducaoTexto[i].CONF_Idioma.Id)

                        <div class="col-md-12">


                            @Html.LabelFor(model => model.MediaIntroducaoTexto[i].Introducao, htmlAttributes: new { @class = "control-label " })
                          
                            @Html.ValidationMessageFor(model => model.MediaIntroducaoTexto[i].Introducao, "", new { @class = "text-danger" })
                            @Html.EditorFor(model => model.MediaIntroducaoTexto[i].Introducao, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })


                        </div>

                    }
                </div>






                <div class="form-group ">
                    @for (int i = 0; i < Model.MediaIntroducaoTexto.Count; i++)
                    {



                        @Html.HiddenFor(model => @Model.MediaIntroducaoTexto[i].CONF_Idioma.Id)

                        <div class="col-md-12">


                            @Html.LabelFor(model => model.MediaIntroducaoTexto[i].Link, htmlAttributes: new { @class = "control-label " })
                  
                            @Html.ValidationMessageFor(model => model.MediaIntroducaoTexto[i].Link, "", new { @class = "text-danger" })
                            @Html.EditorFor(model => model.MediaIntroducaoTexto[i].Link, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })


                        </div>

                    }
                </div>

                <div class="form-group">
                    <div class="col-md-12">
                        <hr />
                    </div>
                </div>

           

                <div class="form-group">
                    @for (int i = 0; i < Model.MediaIntroducaoTexto.Count; i++)
                    {



                        <div class="col-md-12" id="@String.Concat("divImg_", i)">

                            <label class="control-label "><b>Imagem</b></label>
                           
                            @if (!String.IsNullOrWhiteSpace(Model.MediaIntroducaoTexto[i].Imagem))
                            {
                                <p>
                                    <img id="@String.Concat("Img_", i)" src="@String.Concat(@Url.Content("~/Content/files/anexos/"),  Model.MediaIntroducaoTexto[i].Imagem)"
                                         class="img-preview">
                                </p>
                            }
                            else
                            {
                                <p>
                                    <img id="@String.Concat("Img_", i)" src="@Url.Content("~/Content/img/sem-img.jpeg")"
                                         class="img-preview">
                                </p>
                            }






                        </div>



                    }
                </div>






            </div>
        </div>
    </div>





    <div class="form-horizontal">

        <div class="form-group">

            <div class="col-md-12">
                @Html.LabelFor(model => model.MediaIntroducao.Activo, htmlAttributes: new { @class = "control-label " })
                &nbsp;&nbsp;&nbsp;
                @Html.ValidationMessageFor(model => model.MediaIntroducao.Activo, "", new { @class = "text-danger" })
                @Html.CheckBoxFor(model => model.MediaIntroducao.Activo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

            </div>


        </div>



    </div>


</div>



        @using (Ajax.BeginForm("ApagarMediaIntroducaoConfirmar", "Produto", new AjaxOptions { HttpMethod = "POST", OnSuccess = "ApagarMediaIntroducaoSucesso(data)" }
                                      , htmlAttributes: new { @class = "form-horizontal", id = "formRegisto", role = "form" }
                                      ))
        {

            @Html.HiddenFor(x => x.MediaIntroducao.Id)
            <div class="modal-footer">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                        <input type="submit" class="btn btn-primary" value="Confirmar" />
                    </div>
                </div>
            </div>
        }


    </div>
</div>

<style type="text/css">
    .img-preview {
        height: 250px;
        width: auto;
    }

    .pdf {
        color: red;
        font-size: 18px;
        cursor: pointer;
    }

    .parag-pdf:hover {
        text-decoration: underline;
        cursor: pointer;
    }
</style>


<script type="text/javascript">

    /*
    $(document).ready(
        function () {
            var val = $("#PrecoProduto").val();
            val = Number(val);
            $("#PrecoProduto").val(val.numberFormat(2, ',', '.'));
        }
    );
    */

    Number.prototype.numberFormat = function (decimals, dec_point, thousands_sep) {
        dec_point = typeof dec_point !== 'undefined' ? dec_point : '.';
        thousands_sep = typeof thousands_sep !== 'undefined' ? thousands_sep : ',';

        var parts = this.toFixed(decimals).split('.');
        parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, thousands_sep);

        return parts.join(dec_point);
    }
</script>