Webtech_Office/Webtech_Office/Models/ViewModels/ReceitaViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Webtech_Office.Models
{
    public class ReceitaViewModel
    {

           
        public RECE_TipoReceita TipoReceita { get; set; }
        public RECE_Receita Receita { get; set; }
        public List<RECE_ReceitaTexto> ReceitaTexto { get; set; }
        public List<CONF_Idioma> Idioma = new List<CONF_Idioma>();
        public List<ImageUpload> File { get; set; }
        public List<FileDocumento> FileDocumento { get; set; }

        public ReceitaViewModel()
        {
            Receita = new RECE_Receita();
            ReceitaTexto = new List<RECE_ReceitaTexto>();
          
            File = new List<ImageUpload>();
            FileDocumento = new List<Models.FileDocumento>();
        }
    }
}

Webtech_Office/Webtech_Office/Controllers/ReceitaController.cs
using Webtech_Office.Models;
using DataTables.Mvc;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using System.Data.Entity.Core;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Infrastructure;

namespace Webtech_Office.Controllers
{
    [Authorize]
    public class ReceitaController : Controller
    {
        private CMS_DbContext db = new CMS_DbContext();

        // GET: Receita
        public ActionResult Index()
        {
            return View();
        }


        public JsonResult ListaBanner([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel)
        {


            IQueryable<RECE_ReceitaBanner> query = db.RECE_ReceitaBanner
                .Include("RECE_ReceitaBannerTexto")

                .Include("CONF_Idioma")
                .Where(m => m.RECE_ReceitaBannerTexto.Any(mt => mt.CONF_Idioma.Codigo.ToUpper().Equals("PT")));

            var totalCount = query.Count();

            #region Filtering  
            // Applicar filtros para pesquisas 
            if (requestModel.Search.Value != string.Empty)
            {
                var value = requestModel.Search.Value.Trim();

                /*
                  query = 

                      query.Include(m => m.MEDI_MediaTexto.Where(mt => mt.Descricao.Contains(value)))
                           .Include(m => m.MEDI_MediaTexto.Where(mt => mt.Introducao.Contains(value)));
                           */

            }

            var filteredCount = query.Count();

            #endregion Filtering  


            #region Sorting  
            // Sorting  
            var sortedColumns = requestModel.Columns.GetSortedColumns();
            var orderByString = String.Empty;

            foreach (var column in sortedColumns)
            {
                orderByString += orderByString != String.Empty ? "," : "";
                orderByString += (column.Data) + (column.SortDirection == Column.OrderDirection.Ascendant ? " asc" : " desc");
            }

            query = query.OrderBy(x => orderByString == string.Empty ? "Titulo asc" : orderByString);

            #endregion Sorting  

            // Paging  
            query = query.Skip(requestModel.Start).Take(requestModel.Length);



            var data =
                query.Select(m => new
                {

                    Titulo = (m.RECE_ReceitaBannerTexto.FirstOrDefault().Titulo.Length <= 70 ? m.RECE_ReceitaBannerTexto.FirstOrDefault().Titulo
                        : m.RECE_ReceitaBannerTexto.FirstOrDefault().Titulo.Substring(0, 70) + "..."),
                    Introducao = (m.RECE_ReceitaBannerTexto.FirstOrDefault().Introducao.Length <= 70 ? m.RECE_ReceitaBannerTexto.FirstOrDefault().Introducao
                        : m.RECE_ReceitaBannerTexto.FirstOrDefault().Titulo.Substring(0, 70) + "..."),


                    Imagem = m.Id,
                    Link = m.RECE_ReceitaBannerTexto.FirstOrDefault().Link,
                    PDF = m.RECE_ReceitaBannerTexto.FirstOrDefault().PDF,
                    Activo = m.Activo,
                    Opcoes = m.Id

                }).ToList();


            return Json(new DataTablesResponse(requestModel.Draw, data, filteredCount, totalCount), JsonRequestBehavior.AllowGet);





        }

        [HttpGet]
        public ActionResult CriarReceitaBanner()
        {
            ReceitaBannerViewModel model = new ReceitaBannerViewModel();
            model.ReceitaBanner.Activo = true;
            foreach (CONF_Idioma idioma in db.CONF_Idioma.ToList())
            {
                RECE_ReceitaBannerTexto ReceitaTexto = new RECE_ReceitaBannerTexto()
                {
                    CONF_Idioma = idioma
                };
                model.ReceitaBannerTexto.Add(ReceitaTexto);
                ImageUpload file = new ImageUpload();
                model.File.Add(file);
                FileDocumento doc = new FileDocumento();
                model.FileDocumento.Add(doc);

            }




            return View("CriarReceitaBanner", model);

        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CriarReceitaBanner(ReceitaBannerViewModel model)
        {


            model.ReceitaBanner.DataCriacao = DateTime.Now;
            model.ReceitaBanner.DataModificacao = DateTime.Now;



            int i = 0;
            foreach (ImageUpload file in model.File)
            {
                if (file.File != null)
                {
                    string directory = "~/Content/files/anexos/";
                    if (!Directory.Exists(Server.MapPath("~/Content/files/anexos/")))
                    {
                        Directory.CreateDirectory(Server.MapPath("~/Content/files/anexos/"));
                    }

                    var fileName = Guid.NewGuid().ToString()  + Path.GetExtension(file.File.FileName.ToLower());
                    file.File.SaveAs(Path.Combine(Server.MapPath(directory), fileName));

                    model.ReceitaBannerTexto[i].Imagem = fileName;

                }
                i++;

            }
            i = 0;
            foreach (FileDocumento docFile in model.FileDocumento)
            {

                if (docFile.File != null)
                {
                    string directory = "~/Content/files/anexos/";
                    if (!Directory.Exists(Server.MapPath("~/Content/files/anexos/")))
                    {
                        Directory.CreateDirectory(Server.MapPath("~/Content/files/anexos/"));
                    }



                    var fileName = Path.GetFileName(docFile.File.FileName);
                    docFile.File.SaveAs(Path.Combine(Server.MapPath(directory), fileName));

                    model.ReceitaBannerTexto[i].PDF = fileName;

                }
                i++;

            }




            i = 0;
            List<CONF_Idioma> idioma = db.CONF_Idioma.ToList();
            foreach (RECE_ReceitaBannerTexto textos in model.ReceitaBannerTexto)
            {

                textos.RECE_ReceitaBanner = model.ReceitaBanner;
                textos.CONF_Idioma = idioma[i];
              

                i++;

            }



            model.ReceitaBanner.RECE_ReceitaBannerTexto = model.ReceitaBannerTexto;
            db.RECE_ReceitaBanner.Add(model.ReceitaBanner);
            db.SaveChanges();


            /*
            if (!ModelState.IsValid)
            {
                ViewBag.TipoMidia = new SelectList(db.MIDI_TipoMidia.ToList(), "Id", "Descricao");
                ModelState.AddModelError("", "Impossivel criar o Conteudo.");
                return View("CriarMidiaConteudo", model);
            }*/

            return RedirectToAction("Index");

        }


        [HttpGet]
        public ActionResult DetalhesReceitaBanner(int? id)
        {
            RECE_ReceitaBanner model = db.RECE_ReceitaBannerTexto.Include("CONF_Idioma").Include("RECE_ReceitaBanner")
               .Select(x => x.RECE_ReceitaBanner).Where(c => c.Id == id).FirstOrDefault();



            ReceitaBannerViewModel BannerModel = new ReceitaBannerViewModel();
            BannerModel.ReceitaBanner = model;
            BannerModel.ReceitaBannerTexto = model.RECE_ReceitaBannerTexto.ToList();
            BannerModel.Idioma = model.RECE_ReceitaBannerTexto.Select(x => x.CONF_Idioma).ToList();

            return PartialView("_DetalhesReceitaBanner", BannerModel);

        }


        [HttpGet]
        public ActionResult EditarReceitaBanner(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RECE_ReceitaBanner model = db.RECE_ReceitaBannerTexto.Include("CONF_Idioma").Include("RECE_ReceitaBanner")
              .Select(x => x.RECE_ReceitaBanner).Where(c => c.Id == id).FirstOrDefault();


            if (model == null)
            {
                return HttpNotFound();
            }
            ReceitaBannerViewModel BannerModel = new ReceitaBannerViewModel();
            BannerModel.ReceitaBanner = model;
            BannerModel.ReceitaBannerTexto = model.RECE_ReceitaBannerTexto.ToList();
            BannerModel.Idioma = model.RECE_ReceitaBannerTexto.Select(x => x.CONF_Idioma).ToList();


            foreach (CONF_Idioma idioma in db.CONF_Idioma.ToList())
            {


                ImageUpload file = new ImageUpload();
                BannerModel.File.Add(file);
                FileDocumento doc = new FileDocumento();
                BannerModel.FileDocumento.Add(doc);

            }


            return View("EditarReceitaBanner", BannerModel);


        }


        [HttpPost]
        public ActionResult EditarReceitaBanner(ReceitaBannerViewModel model)
        {


            int i = 0;
            foreach (ImageUpload file in model.File)
            {
                if (file.File != null)
                {
                    string directory = "~/Content/files/anexos/";
                    if (!Directory.Exists(Server.MapPath("~/Content/files/anexos/")))
                    {
                        Directory.CreateDirectory(Server.MapPath("~/Content/files/anexos/"));
                    }

                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.File.FileName.ToLower());
                    file.File.SaveAs(Path.Combine(Server.MapPath(directory), fileName));

                    model.ReceitaBannerTexto[i].Imagem = fileName;

                }
                i++;

            }
            i = 0;
            foreach (FileDocumento docFile in model.FileDocumento)
            {

                if (docFile.File != null)
                {
                    string directory = "~/Content/files/anexos/";
                    if (!Directory.Exists(Server.MapPath("~/Content/files/anexos/")))
                    {

Webtech_Office/Webtech_Office/Views/Receita/CriarReceitaBanner.cshtml
@model Webtech_Office.Models.ReceitaBannerViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Inserir Banner</title>
    <script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/jquery")"></script>
    <script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/jqueryval")"></script>
    <script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Bundles/js")"></script>
    <script type="text/javascript" src="~/Scripts/ckeditor/ckeditor.js"></script>
</head>
<body>

    <div class="modal-dialog create-modal">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h3 class="modal-title">Inserir Banner</h3>
            </div>

            <div class="modal-body">
               @using (Html.BeginForm("CriarReceitaBanner", "Receita", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", id = "formRegisto", role = "form" }))
               {
                @Html.AntiForgeryToken()
               
                    <!-- Custom Tabs -->
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="panel panel-primary list-panel" id="list-panel">

                        <div class="panel-heading" style="height:60px;">

                            <h4>Informação</h4>

                        </div>


                        <div class="panel-body  ">

                            <div class="form-horizontal">

                              

                                <div class="form-group">
                              


                                        <div class="col-md-12">
                                            @Html.LabelFor(model => model.ReceitaBanner.Ordem, htmlAttributes: new { @class = "control-label " })
                                      
                                            @Html.ValidationMessageFor(model => model.ReceitaBanner.Ordem, "", new { @class = "text-danger" })
                                            @Html.EditorFor(model => model.ReceitaBanner.Ordem, new { htmlAttributes = new { @class = "form-control" } })

                                        </div>


                                  
                                </div>




                                <div class="form-group">
                                    @for (int i = 0; i < Model.ReceitaBannerTexto.Count; i++)
                                    {
                                        @Html.HiddenFor(model => @Model.ReceitaBannerTexto[i].CONF_Idioma.Id)



                                        <div class="col-md-12">
                                            @Html.LabelFor(model => model.ReceitaBannerTexto[i].Titulo, htmlAttributes: new { @class = "control-label " })
                                            (@Html.DisplayFor(model => model.ReceitaBannerTexto[i].CONF_Idioma.Descricao))
                                            @Html.ValidationMessageFor(model => model.ReceitaBannerTexto[i].Titulo, "", new { @class = "text-danger" })
                                            @Html.EditorFor(model => model.ReceitaBannerTexto[i].Titulo, new { htmlAttributes = new { @class = "form-control" } })

                                        </div>


                                    }
                                </div>

                                <div class="form-group">
                                    @for (int i = 0; i < Model.ReceitaBannerTexto.Count; i++)
                {
                                        @Html.HiddenFor(model => @Model.ReceitaBannerTexto[i].CONF_Idioma.Id)



                                        <div class="col-md-12">
                                            @Html.LabelFor(model => model.ReceitaBannerTexto[i].Introducao, htmlAttributes: new { @class = "control-label " })
                                            (@Html.DisplayFor(model => model.ReceitaBannerTexto[i].CONF_Idioma.Descricao))
                                            @Html.ValidationMessageFor(model => model.ReceitaBannerTexto[i].Introducao, "", new { @class = "text-danger" })
                                            @Html.EditorFor(model => model.ReceitaBannerTexto[i].Introducao, new { htmlAttributes = new { @class = "form-control" } })

                                        </div>


                                    }

                                </div>
                                <div class="form-group">

                                    @for (int i = 0; i < Model.ReceitaBannerTexto.Count; i++)
                                    {
                                        @Html.HiddenFor(model => @Model.ReceitaBannerTexto[i].CONF_Idioma.Id)



                                        <div class="col-md-12">
                                            @Html.LabelFor(model => model.ReceitaBannerTexto[i].Link, htmlAttributes: new { @class = "control-label " })
                                            (@Html.DisplayFor(model => model.ReceitaBannerTexto[i].CONF_Idioma.Descricao))
                                            @Html.ValidationMessageFor(model => model.ReceitaBannerTexto[i].Link, "", new { @class = "text-danger" })
                                            @Html.EditorFor(model => model.ReceitaBannerTexto[i].Link, new { htmlAttributes = new { @class = "form-control" } })

                                        </div>


                                    }
                                </div>

                                <div class="form-group">

                                    @for (int i = 0; i < Model.FileDocumento.Count; i++)
                                    {
                                        @Html.HiddenFor(model => model.ReceitaBannerTexto[i].CONF_Idioma.Id)



                                        <div class="col-md-12">

                                            <label class="control-label "><b>PDF</b></label>
                                            (@Html.DisplayFor(model => model.ReceitaBannerTexto[i].CONF_Idioma.Descricao))
                                            @Html.EditorFor(model => @Model.FileDocumento[i].File, new { htmlAttributes = new { @class = "form-control", name = "File", id = "File" } })



                                        </div>


                                    }
                                </div>
                                <div class="form-group">
                                    @for (int i = 0; i < Model.File.Count; i++)
                                    {
                                        @Html.HiddenFor(model => model.ReceitaBannerTexto[i].CONF_Idioma.Id)



                                        <div class="col-md-12" id="@String.Concat("divImg_", i)">

                                            <label class="control-label "><b>Imagem</b></label>
                                            (@Html.DisplayFor(model => model.ReceitaBannerTexto[i].CONF_Idioma.Descricao))
                                            @Html.EditorFor(model => @Model.File[i].File, new { htmlAttributes = new { @class = "form-control ", name = @String.Concat("File_", i), @id = @String.Concat("File_", i) } })
                                            <img id="@String.Concat("Img_", i)" class="img-preview">
                                            <script type="text/javascript">
                                                $("@String.Concat("#File_", i+"__File")").change(function () {
                                                    readURL(this, "@String.Concat("#Img_", i)");
                                                });
                                            </script>

                                        </div>


                                    }
                                </div>
                    </div>
                 </div>
                   </div>

                  


                       
                            <div class="form-horizontal">

                                <div class="form-group">

                                    <div class="col-md-12">
                                        @Html.LabelFor(model => model.ReceitaBanner.Activo, htmlAttributes: new { @class = "control-label " })
                                        &nbsp;&nbsp;&nbsp;
                                        @Html.ValidationMessageFor(model => model.ReceitaBanner.Activo, "", new { @class = "text-danger" })
                                        @Html.CheckBoxFor(model => model.ReceitaBanner.Activo, new { htmlAttributes = new { @class = "form-control" } })

                                    </div>
                                </div>



                            </div>
             



                  


             
                        <div class="modal-footer">
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <button type="button" class="btn btn-default" data-dismiss="modal" >Fechar</button>
                                    <input type="submit" class="btn btn-primary" value="Confirmar" />
                                </div>
                            </div>
                        </div>
                     

                   
               }
              
          </div>
      </div>
   </div>

            <style type="text/css">
                .img-preview {
                    height: 250px;
                    width: auto;
                    display: none;
                }
            </style>

            <script type="text/javascript">

                                                $("#CancelRedirect").click(
                                                    function () {
                                                        window.location = "/Receita/Index";
                                                    }
                                                );



                                                function readURL(input, img) {
                                                    for (var i = 0; i < input.files.length; i++) {
                                                        if (input.files[i]) {
                                                            var reader = new FileReader();

                                                            reader.onload = function (e) {
                                                                $(img).attr('src', e.target.result);
                                                                $(img).css("display", "block");
                                                            }
                                                            reader.readAsDataURL(input.files[i]);
                                                        }
                                                    }


                                                }

                                                $(document).ready(
                                                    function () {

                                                        $("#MapaPartilhado").change(

                                                            function () {
                                                                var mapa = $("#MapaPartilhado").val();
                                                                document.getElementById("#DivMapaPreview").innerHTML = "";
                                                                document.getElementById("#DivMapaPreview").innerHTML = mapa;
                                                            }
                                                        );
                                                    }

                                                );




            </script>
</body>
</html>

Webtech_Office/Webtech_Office/Views/Receita/_ApagarReceitaCozinheiroPartial.cshtml
@model  Webtech_Office.Models.CozinheiroViewModel


<script type="text/javascript" src="~/Scripts/ckeditor/ckeditor.js"></script>


<div class="modal-dialog create-modal">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title">Apagar Cozinheiro</h4>
        </div>
     
            <div class="modal-body">

                <div class="panel panel-primary list-panel" id="list-panel">

                    <div class="panel-heading" style="height:60px;">

                        <h4>Informação</h4>

                    </div>


                    <div class="panel-body  ">

                        <div class="form-horizontal">



                            <div class="form-group">



                                <div class="col-md-12">
                                    @Html.LabelFor(model => model.Cozinheiro.Ordem, htmlAttributes: new { @class = "control-label " })

                                    @Html.ValidationMessageFor(model => model.Cozinheiro.Ordem, "", new { @class = "text-danger" })
                                    @Html.EditorFor(model => model.Cozinheiro.Ordem, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                                </div>



                            </div>

                            <div class="form-group">



                                <div class="col-md-12">
                                    @Html.LabelFor(model => model.Cozinheiro.Nome, htmlAttributes: new { @class = "control-label " })

                                    @Html.ValidationMessageFor(model => model.Cozinheiro.Nome, "", new { @class = "text-danger" })
                                    @Html.EditorFor(model => model.Cozinheiro.Nome, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                                </div>



                            </div>


                            <div class="form-group">



                                <div class="col-md-12">
                                    @Html.LabelFor(model => model.Cozinheiro.Email, htmlAttributes: new { @class = "control-label " })

                                    @Html.ValidationMessageFor(model => model.Cozinheiro.Email, "", new { @class = "text-danger" })
                                    @Html.EditorFor(model => model.Cozinheiro.Email, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                                </div>



                            </div>





                            <div class="form-group">
                                @for (int i = 0; i < Model.CozinheiroTexto.Count; i++)
                                {
                                    @Html.HiddenFor(model => @Model.CozinheiroTexto[i].CONF_Idioma.Id)



                                    <div class="col-md-12">
                                        @Html.LabelFor(model => model.CozinheiroTexto[i].Introducao, htmlAttributes: new { @class = "control-label " })
                                        (@Html.DisplayFor(model => model.CozinheiroTexto[i].CONF_Idioma.Descricao))
                                        @Html.ValidationMessageFor(model => model.CozinheiroTexto[i].Introducao, "", new { @class = "text-danger" })
                                        @Html.EditorFor(model => model.CozinheiroTexto[i].Introducao, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                                    </div>


                                }

                            </div>
                            <div class="form-group">

                                @for (int i = 0; i < Model.CozinheiroTexto.Count; i++)
                                {
                                    @Html.HiddenFor(model => @Model.CozinheiroTexto[i].CONF_Idioma.Id)



                                    <div class="col-md-12">
                                        @Html.LabelFor(model => model.CozinheiroTexto[i].Link, htmlAttributes: new { @class = "control-label " })
                                        (@Html.DisplayFor(model => model.CozinheiroTexto[i].CONF_Idioma.Descricao))
                                        @Html.ValidationMessageFor(model => model.CozinheiroTexto[i].Link, "", new { @class = "text-danger" })
                                        @Html.EditorFor(model => model.CozinheiroTexto[i].Link, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                                    </div>


                                }
                            </div>


                            <div class="form-group">



                                <div class="col-md-12" id="imgCoz">

                                    <label class="control-label "><b>Imagem</b></label>

                                    @if (!String.IsNullOrWhiteSpace(Model.Cozinheiro.Imagem))
                                    {
                                        <p>
                                            <img id="imgCoz" src="@String.Concat(@Url.Content("~/Content/files/anexos/"),  Model.Cozinheiro.Imagem)"
                                                 class="img-preview">
                                        </p>
                                    }
                                    else
                                    {
                                        <p>
                                            <img id="imgCoz" src="@Url.Content("~/Content/img/sem-img.jpeg")"
                                                 class="img-preview">
                                        </p>
                                    }


                                </div>



                            </div>
                        </div>
                    </div>
                </div>





                <div class="form-horizontal">

                    <div class="form-group">

                        <div class="col-md-12">
                            @Html.LabelFor(model => model.Cozinheiro.Activo, htmlAttributes: new { @class = "control-label " })
                            &nbsp;&nbsp;&nbsp;
                            @Html.ValidationMessageFor(model => model.Cozinheiro.Activo, "", new { @class = "text-danger" })
                            @Html.CheckBoxFor(model => model.Cozinheiro.Activo, new { htmlAttributes = new { @class = "form-control" } })

                        </div>
                    </div>



                </div>

                @if (ViewBag.ApagarRelacao != null)
                {
                    <p style="padding:0;color:#ff0000;">O Cozinheiro não pode ser apagado por ter receitas relacionadas.</p>
                }

            </div>

     

@using (@Html.BeginForm("ApagarReceitaCozinheiroConfirmar", "Receita", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {

    @Html.HiddenFor(x => x.Cozinheiro.Id)
            <div class="modal-footer">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>

                        @if (ViewBag.ApagarRelacao != null)
                        {
                            <input  class="btn btn-primary" value="Confirmar" disabled="disabled" />
                        }
                        else
                        {
                            <input type="submit" class="btn btn-primary" value="Confirmar" />
                        }

                       
                    </div>
                </div>
            </div>
        }

    </div>
</div>