Webtech_Office/Webtech_Office/Controllers/ResponsabilidadeSocialController.cs
using DataTables.Mvc;
using System;
using System.Collections.Generic;
using System.Data.Entity.SqlServer;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Webtech_Office.Models;

namespace Webtech_Office.Controllers
{
    public class ResponsabilidadeSocialController : Controller
    {
        private CMS_DbContext db = new CMS_DbContext();

        // GET: RespSocial
        public ActionResult Index()
        {
            return View();
        }




        public JsonResult ListaRespSocialIntroducao([ModelBinder(typeof(DataTablesBinder))] IDataTablesRequest requestModel)
        {


            IQueryable<RESP_RespSocialIntroducao> query = db.RESP_RespSocialIntroducao
                .Include("RESP_RespSocialIntroducaoTexto")

                .Include("CONF_Idioma")
                .Where(m => m.RESP_RespSocialIntroducaoTexto.Any(mt => mt.CONF_Idioma.Codigo.ToUpper().Equals("PT")));

            var totalCount = query.Count();

            #region Filtering  
            // Applicar filtros para pesquisas 
            if (requestModel.Search.Value != string.Empty)
            {
                var value = requestModel.Search.Value.Trim();

                /*
                  query = 

                      query.Include(m => m.MEDI_MediaTexto.Where(mt => mt.Descricao.Contains(value)))
                           .Include(m => m.MEDI_MediaTexto.Where(mt => mt.Introducao.Contains(value)));
                           */

            }

            var filteredCount = query.Count();

            #endregion Filtering  


            #region Sorting  
            // Sorting  
            var sortedColumns = requestModel.Columns.GetSortedColumns();
            var orderByString = String.Empty;

            foreach (var column in sortedColumns)
            {
                orderByString += orderByString != String.Empty ? "," : "";
                orderByString += (column.Data) + (column.SortDirection == Column.OrderDirection.Ascendant ? " asc" : " desc");
            }

            query = query.OrderBy(x => orderByString == string.Empty ? "Titulo asc" : orderByString);

            #endregion Sorting  

            // Paging  
            query = query.Skip(requestModel.Start).Take(requestModel.Length);



            var data =
                query.Select(m => new
                {

                    Titulo = (m.RESP_RespSocialIntroducaoTexto.FirstOrDefault().Titulo.Length <= 70 ? m.RESP_RespSocialIntroducaoTexto.FirstOrDefault().Titulo
                        : m.RESP_RespSocialIntroducaoTexto.FirstOrDefault().Titulo.Substring(0, 70) + "..."),
                    Introducao = (m.RESP_RespSocialIntroducaoTexto.FirstOrDefault().Introducao.Length <= 70 ? m.RESP_RespSocialIntroducaoTexto.FirstOrDefault().Introducao
                        : m.RESP_RespSocialIntroducaoTexto.FirstOrDefault().Titulo.Substring(0, 70) + "..."),


                    Imagem = m.Id,

                    Activo = m.Activo,
                    Opcoes = m.Id

                }).ToList();


            return Json(new DataTablesResponse(requestModel.Draw, data, filteredCount, totalCount), JsonRequestBehavior.AllowGet);





        }


        [HttpGet]
        public ActionResult CriarRespSocialIntroducao()
        {
            RespSocialIntroducaoViewModel model = new RespSocialIntroducaoViewModel();
            model.RespSocialIntroducao.Activo = true;
            foreach (CONF_Idioma idioma in db.CONF_Idioma.ToList())
            {
                RESP_RespSocialIntroducaoTexto RespSocialTexto = new RESP_RespSocialIntroducaoTexto()
                {
                    CONF_Idioma = idioma
                };
                model.RespSocialIntroducaoTexto.Add(RespSocialTexto);
                ImageUpload file = new ImageUpload();
                model.File.Add(file);
                FileDocumento doc = new FileDocumento();
                model.FileDocumento.Add(doc);

            }

            return View("CriarRespSocialIntroducao", model);
        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult CriarRespSocialIntroducao(RespSocialIntroducaoViewModel model)
        {


            model.RespSocialIntroducao.DataCriacao = DateTime.Now;
            model.RespSocialIntroducao.DataModificacao = DateTime.Now;

            int i = 0;
            foreach (ImageUpload file in model.File)
            {
                if (file.File != null)
                {
                    string directory = "~/Content/files/anexos/";
                    if (!Directory.Exists(Server.MapPath("~/Content/files/anexos/")))
                    {
                        Directory.CreateDirectory(Server.MapPath("~/Content/files/anexos/"));
                    }

                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.File.FileName.ToLower());
                    file.File.SaveAs(Path.Combine(Server.MapPath(directory), fileName));

                    model.RespSocialIntroducaoTexto[i].Imagem = fileName;

                }
                i++;

            }
            i = 0;
            foreach (FileDocumento docFile in model.FileDocumento)
            {

                if (docFile.File != null)
                {
                    string directory = "~/Content/files/anexos/";
                    if (!Directory.Exists(Server.MapPath("~/Content/files/anexos/")))
                    {
                        Directory.CreateDirectory(Server.MapPath("~/Content/files/anexos/"));
                    }



                    var fileName = Path.GetFileName(docFile.File.FileName);
                    docFile.File.SaveAs(Path.Combine(Server.MapPath(directory), fileName));

                    model.RespSocialIntroducaoTexto[i].PDF = fileName;

                }
                i++;

            }




            i = 0;
            List<CONF_Idioma> idioma = db.CONF_Idioma.ToList();
            foreach (RESP_RespSocialIntroducaoTexto textos in model.RespSocialIntroducaoTexto)
            {

                textos.RESP_RespSocialIntroducao = model.RespSocialIntroducao;
                textos.CONF_Idioma = idioma[i];
                textos.Introducao = System.Net.WebUtility.HtmlDecode(textos.Introducao);

                i++;

            }



            model.RespSocialIntroducao.RESP_RespSocialIntroducaoTexto = model.RespSocialIntroducaoTexto;
            db.RESP_RespSocialIntroducao.Add(model.RespSocialIntroducao);
            db.SaveChanges();


            /*
            if (!ModelState.IsValid)
            {
                ViewBag.TipoMidia = new SelectList(db.MIDI_TipoMidia.ToList(), "Id", "Descricao");
                ModelState.AddModelError("", "Impossivel criar o Conteudo.");
                return View("CriarMidiaConteudo", model);
            }*/

            return RedirectToAction("Index");

        }





        [HttpGet]
        public ActionResult DetalhesRespSocialIntroducao(int? id)
        {
            RESP_RespSocialIntroducao model = db.RESP_RespSocialIntroducaoTexto.Include("CONF_Idioma").Include("RESP_RespSocialIntroducao")
               .Select(x => x.RESP_RespSocialIntroducao).Where(c => c.Id == id).FirstOrDefault();



            RespSocialIntroducaoViewModel IntroducaoModel = new RespSocialIntroducaoViewModel();
            IntroducaoModel.RespSocialIntroducao = model;
            IntroducaoModel.RespSocialIntroducaoTexto = model.RESP_RespSocialIntroducaoTexto.ToList();
            IntroducaoModel.Idioma = model.RESP_RespSocialIntroducaoTexto.Select(x => x.CONF_Idioma).ToList();

            return PartialView("_DetalhesRespSocialIntroducao", IntroducaoModel);

        }


        [HttpGet]
        public ActionResult EditarRespSocialIntroducao(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            RESP_RespSocialIntroducao model = db.RESP_RespSocialIntroducaoTexto.Include("CONF_Idioma").Include("RESP_RespSocialIntroducao")
              .Select(x => x.RESP_RespSocialIntroducao).Where(c => c.Id == id).FirstOrDefault();


            if (model == null)
            {
                return HttpNotFound();
            }
            RespSocialIntroducaoViewModel IntroducaoModel = new RespSocialIntroducaoViewModel();
            IntroducaoModel.RespSocialIntroducao = model;
            IntroducaoModel.RespSocialIntroducaoTexto = model.RESP_RespSocialIntroducaoTexto.ToList();
            IntroducaoModel.Idioma = model.RESP_RespSocialIntroducaoTexto.Select(x => x.CONF_Idioma).ToList();


            foreach (CONF_Idioma idioma in db.CONF_Idioma.ToList())
            {


                ImageUpload file = new ImageUpload();
                IntroducaoModel.File.Add(file);
                FileDocumento doc = new FileDocumento();
                IntroducaoModel.FileDocumento.Add(doc);

            }


            return View("EditarRespSocialIntroducao", IntroducaoModel);


        }

        [HttpPost]
        [ValidateInput(false)]
        public ActionResult EditarRespSocialIntroducao(RespSocialIntroducaoViewModel model)
        {


            int i = 0;
            foreach (ImageUpload file in model.File)
            {
                if (file.File != null)
                {
                    string directory = "~/Content/files/anexos/";
                    if (!Directory.Exists(Server.MapPath("~/Content/files/anexos/")))
                    {
                        Directory.CreateDirectory(Server.MapPath("~/Content/files/anexos/"));
                    }

                    var fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.File.FileName.ToLower());
                    file.File.SaveAs(Path.Combine(Server.MapPath(directory), fileName));

                    model.RespSocialIntroducaoTexto[i].Imagem = fileName;

                }
                i++;

            }
            i = 0;

Webtech_Office/Webtech_Office/Views/ResponsabilidadeSocial/CriarRespSocial.cshtml
@model Webtech_Office.Models.RespSocialViewModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Inserir Introducao</title>
    <script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/jquery")"></script>
    <script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/jqueryval")"></script>
    <script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Bundles/js")"></script>
    <script type="text/javascript" src="~/Scripts/ckeditor/ckeditor.js"></script>

    <script type="text/javascript">
        $(document).ready(
            function () {
                waitingDialog.hide();

            }
        );
    </script>

</head>
<body>

    <div class="modal-dialog create-modal">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
                <h3 class="modal-title">Inserir Responsabilidade Social</h3>
            </div>

            <div class="modal-body">
                @using (Html.BeginForm("CriarRespSocial", "ResponsabilidadeSocial", FormMethod.Post, new { enctype = "multipart/form-data", @class = "form-horizontal", id = "formRegisto", role = "form" }))
                {
                    @Html.AntiForgeryToken()

                    <!-- Custom Tabs -->
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="panel panel-primary list-panel" id="list-panel">

                        <div class="panel-heading" style="height:60px;">

                            <h4>Informação</h4>

                        </div>


                        <div class="panel-body  ">

                            <div class="form-horizontal">



                                <div class="form-group">
                                   

                                        <div class="col-md-3">
                                            @Html.LabelFor(model => model.RespSocial.DataEvento, htmlAttributes: new { @class = "control-label " })

                                            @Html.ValidationMessageFor(model => model.RespSocial.DataEvento, "", new { @class = "text-danger" })
                                            @Html.EditorFor(model => model.RespSocial.DataEvento, "{dd-MM-yyyy}", new { htmlAttributes = new { @class = "form-control datepicker" } })

                                        </div>

                                    <div class="col-md-9">
                                     
                                    </div>


                                   
                                </div>




                                <div class="form-group">
                                    @for (int i = 0; i < Model.RespSocialTexto.Count; i++)
                                    {
                                        @Html.HiddenFor(model => @Model.RespSocialTexto[i].CONF_Idioma.Id)



                                        <div class="col-md-12">
                                            @Html.LabelFor(model => model.RespSocialTexto[i].Titulo, htmlAttributes: new { @class = "control-label " })
                                            
                                            @Html.ValidationMessageFor(model => model.RespSocialTexto[i].Titulo, "", new { @class = "text-danger" })
                                            @Html.EditorFor(model => model.RespSocialTexto[i].Titulo, new { htmlAttributes = new { @class = "form-control" } })

                                        </div>


                                    }
                                </div>

                                <div class="form-group">
                                    @for (int i = 0; i < Model.RespSocialTexto.Count; i++)
                {
                                        @Html.HiddenFor(model => @Model.RespSocialTexto[i].CONF_Idioma.Id)



                                        <div class="col-md-12">
                                            @Html.LabelFor(model => model.RespSocialTexto[i].Introducao, htmlAttributes: new { @class = "control-label " })
                                        
                                            @Html.ValidationMessageFor(model => model.RespSocialTexto[i].Introducao, "", new { @class = "text-danger" })
                                            @Html.EditorFor(model => model.RespSocialTexto[i].Introducao, new { htmlAttributes = new { @class = "form-control" } })

                                        </div>


                                    }

                                </div>

                                

                                <div class="form-group">

                                    @for (int i = 0; i < Model.RespSocialTexto.Count; i++)
                                    {
                                        @Html.HiddenFor(model => @Model.RespSocialTexto[i].CONF_Idioma.Id)



                                        <div class="col-md-12">
                                            @Html.LabelFor(model => model.RespSocialTexto[i].Link, htmlAttributes: new { @class = "control-label " })
                                           
                                            @Html.ValidationMessageFor(model => model.RespSocialTexto[i].Link, "", new { @class = "text-danger" })
                                            @Html.EditorFor(model => model.RespSocialTexto[i].Link, new { htmlAttributes = new { @class = "form-control" } })

                                        </div>


                                    }
                                </div>

                                <div class="form-group">

                                    @for (int i = 0; i < Model.RespSocialTexto.Count; i++)
                                    {
                                        @Html.HiddenFor(model => @Model.RespSocialTexto[i].CONF_Idioma.Id)


                                        <div class="col-md-12">
                                            @Html.LabelFor(model => model.RespSocialTexto[i].Conteudo, htmlAttributes: new { @class = "control-label " })

                                            @Html.ValidationMessageFor(model => model.RespSocialTexto[i].Conteudo, "", new { @class = "text-danger" })
                                            @Html.TextAreaFor(model => model.RespSocialTexto[i].Conteudo, new { @rows = 200, @class = "form-control", id = @i })
                                            <script>
                                                $(document).ready(
                                                    function () {
                                                        CKEDITOR.replace('@i');
                                                        CKEDITOR.Add;
                                                    }
                                                );

                                            </script>
                                        </div>

                                    }
                                </div>

                                <div class="form-group">

                                    @for (int i = 0; i < Model.FileDocumento.Count; i++)
                                    {
                                        @Html.HiddenFor(model => model.RespSocialTexto[i].CONF_Idioma.Id)



                                        <div class="col-md-12">

                                            <label class="control-label "><b>Anexo</b></label>
                                           
                                            @Html.EditorFor(model => @Model.FileDocumento[i].File, new { htmlAttributes = new { @class = "form-control", name = "File", id = "File" } })



                                        </div>


                                    }
                                </div>

                                <div class="form-group">
                                    <div class="col-md-12">
                                        <hr />
                                    </div>
                                </div>

                                <div class="form-group">
                                    @for (int i = 0; i < Model.File.Count; i++)
                                    {
                                        @Html.HiddenFor(model => model.RespSocialTexto[i].CONF_Idioma.Id)



                                        <div class="col-md-12" id="@String.Concat("divImg_", i)">

                                            <label class="control-label "><b>Imagem</b></label>
                                  
                                            @Html.EditorFor(model => @Model.File[i].File, new { htmlAttributes = new { @class = "form-control ", name = @String.Concat("File_", i), @id = @String.Concat("File_", i) } })
                                            <img id="@String.Concat("Img_", i)" class="img-preview">
                                            <script type="text/javascript">
                                                $("@String.Concat("#File_", i+"__File")").change(function () {
                                                    readURL(this, "@String.Concat("#Img_", i)");
                                                });
                                            </script>

                                        </div>


                                    }
                                </div>

                                <div class="form-horizontal">

                                    <div class="form-group">

                                        <div class="col-md-12">
                                            @Html.LabelFor(model => model.RespSocial.Activo, htmlAttributes: new { @class = "control-label " })
                                            &nbsp;&nbsp;&nbsp;
                                            @Html.ValidationMessageFor(model => model.RespSocial.Activo, "", new { @class = "text-danger" })
                                            @Html.CheckBoxFor(model => model.RespSocial.Activo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

                                        </div>


                                    </div>



                                </div>

                            </div>
                        </div>
                    </div>











                            <div class="modal-footer">
                                <div class="form-group">
                                    <div class="col-md-offset-2 col-md-10">
                                        <button type="button" class="btn btn-default" data-dismiss="modal" >Fechar</button>
                                        <input type="submit" class="btn btn-primary" value="Confirmar" />
                                    </div>
                                </div>
                            </div>



                }

            </div>
        </div>
    </div>

    <style type="text/css">
        .img-preview {
            height: 250px;
            width: auto;
            
        }
    </style>

    <script type="text/javascript">

        $("#CancelRedirect").click(
            function () {
                window.location = "/RespSocial/Index";
            }
        );



        function readURL(input, img) {
            for (var i = 0; i < input.files.length; i++) {
                if (input.files[i]) {
                    var reader = new FileReader();

                    reader.onload = function (e) {
                        $(img).attr('src', e.target.result);
                        $(img).css("display", "block");
                    }
                    reader.readAsDataURL(input.files[i]);
                }
            }


        }

        $(document).ready(
            function () {

                $("#MapaPartilhado").change(

                    function () {
                        var mapa = $("#MapaPartilhado").val();
                        document.getElementById("#DivMapaPreview").innerHTML = "";
                        document.getElementById("#DivMapaPreview").innerHTML = mapa;
                    }
                );
            }

        );




    </script>
</body>
</html>

Webtech_Office/Webtech_Office/Views/ResponsabilidadeSocial/_ApagarRespSocialIntroducaoPartial.cshtml
@model Webtech_Office.Models.RespSocialIntroducaoViewModel

<script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/jquery")"></script>
<script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/jqueryval")"></script>
<script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Bundles/js")"></script>
<script type="text/javascript" src="~/Scripts/ckeditor/ckeditor.js"></script>

<script type="text/javascript">
    $(document).ready(
        function () {
            waitingDialog.hide();

        }
    );
</script>



<div class="modal-dialog create-modal">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>
            <h4 class="modal-title">Apagar Introdução</h4>
        </div>

        <div class="modal-body">
    <!-- Custom Tabs -->

    <div class="panel panel-primary list-panel" id="list-panel">

        <div class="panel-heading" style="height:60px;">

            <h4>Informação</h4>

        </div>


        <div class="panel-body  ">
            <div class="form-horizontal">

                <div class="form-group  ">
                    @for (int i = 0; i < Model.RespSocialIntroducaoTexto.Count; i++)
                    {
                        @Html.HiddenFor(model => @Model.RespSocialIntroducaoTexto[i].CONF_Idioma.Id)

                        <div class="col-md-12">


                            @Html.LabelFor(model => model.RespSocialIntroducaoTexto[i].Titulo, htmlAttributes: new { @class = "control-label " })
                           
                            @Html.ValidationMessageFor(model => model.RespSocialIntroducaoTexto[i].Titulo, "", new { @class = "text-danger" })
                            @Html.EditorFor(model => model.RespSocialIntroducaoTexto[i].Titulo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })


                        </div>

                    }
                </div>


                <div class="form-group ">
                    @for (int i = 0; i < Model.RespSocialIntroducaoTexto.Count; i++)
                    {
                        @Html.HiddenFor(model => @Model.RespSocialIntroducaoTexto[i].CONF_Idioma.Id)

                        <div class="col-md-12">


                            @Html.LabelFor(model => model.RespSocialIntroducaoTexto[i].Introducao, htmlAttributes: new { @class = "control-label " })
                     
                            @Html.ValidationMessageFor(model => model.RespSocialIntroducaoTexto[i].Introducao, "", new { @class = "text-danger" })
                            @Html.EditorFor(model => model.RespSocialIntroducaoTexto[i].Introducao, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })


                        </div>

                    }
                </div>






                <div class="form-group ">
                    @for (int i = 0; i < Model.RespSocialIntroducaoTexto.Count; i++)
                    {



                        @Html.HiddenFor(model => @Model.RespSocialIntroducaoTexto[i].CONF_Idioma.Id)

                        <div class="col-md-12">


                            @Html.LabelFor(model => model.RespSocialIntroducaoTexto[i].Link, htmlAttributes: new { @class = "control-label " })
                        
                            @Html.ValidationMessageFor(model => model.RespSocialIntroducaoTexto[i].Link, "", new { @class = "text-danger" })
                            @Html.EditorFor(model => model.RespSocialIntroducaoTexto[i].Link, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })


                        </div>

                    }
                </div>

                <div class="form-group">
                    <div class="col-md-12">
                        <hr />
                    </div>
                </div>

              
                <div class="form-group">
                    @for (int i = 0; i < Model.RespSocialIntroducaoTexto.Count; i++)
                    {



                        <div class="col-md-12" id="@String.Concat("divImg_", i)">

                            <label class="control-label "><b>Imagem</b></label>
                            (@Html.DisplayFor(model => model.RespSocialIntroducaoTexto[i].CONF_Idioma.Descricao))
                            @if (!String.IsNullOrWhiteSpace(Model.RespSocialIntroducaoTexto[i].Imagem))
                            {
                                <p>
                                    <img id="@String.Concat("Img_", i)" src="@String.Concat(@Url.Content("~/Content/files/anexos/"),  Model.RespSocialIntroducaoTexto[i].Imagem)"
                                         class="img-preview">
                                </p>
                            }
                            else
                            {
                                <p>
                                    <img id="@String.Concat("Img_", i)" src="@Url.Content("~/Content/img/sem-img.jpeg")"
                                         class="img-preview">
                                </p>
                            }






                        </div>



                    }
                </div>






            </div>
        </div>
    </div>





    <div class="form-horizontal">

        <div class="form-group">

            <div class="col-md-12">
                @Html.LabelFor(model => model.RespSocialIntroducao.Activo, htmlAttributes: new { @class = "control-label " })
                &nbsp;&nbsp;&nbsp;
                @Html.ValidationMessageFor(model => model.RespSocialIntroducao.Activo, "", new { @class = "text-danger" })
                @Html.CheckBoxFor(model => model.RespSocialIntroducao.Activo, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })

            </div>


        </div>



    </div>


</div>



        @using (Html.BeginForm("ApagarRespSocialIntroducaoConfirmar", "ResponsabilidadeSocial", FormMethod.Post
                                      , htmlAttributes: new { @class = "form-horizontal", id = "formRegisto", role = "form" }
                                      ))
        {

            @Html.HiddenFor(x => x.RespSocialIntroducao.Id)
            <div class="modal-footer">
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
                        <input type="submit" class="btn btn-primary" value="Confirmar" />
                    </div>
                </div>
            </div>
        }


    </div>
</div>

<style type="text/css">
    .img-preview {
        height: 250px;
        width: auto;
    }

    .pdf {
        color: red;
        font-size: 18px;
        cursor: pointer;
    }

    .parag-pdf:hover {
        text-decoration: underline;
        cursor: pointer;
    }
</style>


<script type="text/javascript">

    /*
    $(document).ready(
        function () {
            var val = $("#PrecoProduto").val();
            val = Number(val);
            $("#PrecoProduto").val(val.numberFormat(2, ',', '.'));
        }
    );
    */

    Number.prototype.numberFormat = function (decimals, dec_point, thousands_sep) {
        dec_point = typeof dec_point !== 'undefined' ? dec_point : '.';
        thousands_sep = typeof thousands_sep !== 'undefined' ? thousands_sep : ',';

        var parts = this.toFixed(decimals).split('.');
        parts[0] = parts[0].replace(/\B(?=(\d{3})+(?!\d))/g, thousands_sep);

        return parts.join(dec_point);
    }
</script>

Webtech_Office/Webtech_Office/Views/ResponsabilidadeSocial/_ImagemPreviewPartial.cshtml
@model Webtech_Office.Models.ImagemViewModel
@{
    Layout = null;
}
<script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/jquery")"></script>
<script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/bundles/jqueryval")"></script>
<script src="@System.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/Bundles/js")"></script>
<script type="text/javascript" src="~/Scripts/ckeditor/ckeditor.js"></script>
<section class="content-header">
    <h1>
        <i class="fa fa-picture-o" aria-hidden="true"></i> Banner

    </h1>
</section>

<div class="modal-dialog create-modal" style="width:70%!important;">
    <div class="modal-content">
        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">×</span>
            </button>

        </div>

        <img src="@String.Concat(@Url.Content("~/Content/files/anexos/"), Model.Imagem)" style="width:100%;height:500px;" />

    </div>
</div>